name: 'ROS industrial_ci'
description: "Running various CI checks for ROS package repositories"

inputs:
  config:
    description: 'Configuration in JSON format, e.g. from matrix'
    required: false
runs:
  using: 'node12'
  main: '.github/action.js'
