name: Legacy

on:
  push:
  pull_request:
  # schedule: https://github.com/ros-industrial/industrial_ci/blob/master/.github/workflows/legacy.yml

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://koalaman/shellcheck-alpine
        with:
          args: /bin/sh -c "shellcheck -x *.sh industrial_ci/scripts/*_ci industrial_ci/src/*.sh industrial_ci/src/*/*.sh"
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./ci.sh
        env: ${{matrix.env}}
